# Generated by Django 4.2.23 on 2025-10-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
