# Generated by Django 4.2.23 on 2025-10-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orders_payment_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
