# Generated by Django 4.2.23 on 2025-10-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orders_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_request_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment_status',
        ),
    ]
