# Generated by Django 4.2.23 on 2025-10-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blgpost_chead0_blgpost_chead1_blgpost_chead2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blgpost',
            name='chead0',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blgpost',
            name='chead1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blgpost',
            name='chead2',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
