# Generated by Django 4.2.23 on 2025-10-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blgpost_chead0_alter_blgpost_chead1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blgpost',
            new_name='Blogpost',
        ),
    ]
